### ISSUE TITLE
Stato batteria 

### ISSUE THREAD

**Issue by PaulusThe1** [muchasuerte/ha-besmart#9]
Ciao. Il termostato mi indica che le batterie sono scariche, ma su HA il sensore "batteria" mi continua a dare il valore "normale"

**Comment by faxbio** [comment]
Provo a darci un occhio appena riesco, ma in questi giorni il server
besmart è sempre offline ( o meglio , busy)...sicuro non sia quello?
Da app ti colleghi?

Il sab 23 lug 2022, 20:11 PaulusThe1 ***@***.***> ha scritto:

**Comment by PaulusThe1** [comment]
Io mi collego regolarmente sia con l'app BeSmart che con HomeAssistant
-------- Messaggio originale --------Da: faxbio ***@***.***> Data: 11/10/22  10:53  (GMT+01:00) A: muchasuerte/ha-besmart ***@***.***> Cc: PaulusThe1 ***@***.***>, Author ***@***.***> Oggetto: Re: [muchasuerte/ha-besmart] Stato batteria  (Issue #9) 

Provo a darci un occhio appena riesco, ma in questi giorni il server

besmart è sempre offline ( o meglio , busy)...sicuro non sia quello?

Da app ti colleghi?



Il sab 23 lug 2022, 20:11 PaulusThe1 ***@***.***> ha scritto:

**Comment by faxbio** [comment]
Effettivamente adesso che mi funziona (stranamente 😝 ) la app anche la mia batteria scarica non viene piu’ segnalata.

Io mi ero appoggiato al codice di muchasuerte non ho le competenze necessarie per verificare se il valore dello status batteria viene ancora esportato correttamente verso HA, ci tocca aspettare lui o altri volenterosi…

 

Da: PaulusThe1 ***@***.***> 
Inviato: martedì 11 ottobre 2022 11:28
A: muchasuerte/ha-besmart ***@***.***>
Cc: faxbio ***@***.***>; Comment ***@***.***>
Oggetto: Re: [muchasuerte/ha-besmart] Stato batteria (Issue #9)

 

Io mi collego regolarmente sia con l'app BeSmart che con HomeAssistant
-------- Messaggio originale --------Da: faxbio ***@***.*** <mailto:***@***.***> > Data: 11/10/22 10:53 (GMT+01:00) A: muchasuerte/ha-besmart ***@***.*** <mailto:***@***.***> > Cc: PaulusThe1 ***@***.*** <mailto:***@***.***> >, Author ***@***.*** <mailto:***@***.***> > Oggetto: Re: [muchasuerte/ha-besmart] Stato batteria (Issue #9) 

Provo a darci un occhio appena riesco, ma in questi giorni il server

besmart è sempre offline ( o meglio , busy)...sicuro non sia quello?

Da app ti colleghi?



Il sab 23 lug 2022, 20:11 PaulusThe1 ***@***.*** <mailto:***@***.***> > ha scritto:

**Comment by faxbio** [comment]
Alla fine con un po di pazienza ho invece trovato cosa non va. 

Da Gennaio probabilmente , non viene piu’ settato l’attributo battery perche’ non accettato dal climate component.

 

Cambiando il device_state_attribute in extra_state_attribute torna a funzionare.

 

Ho creato la pull req, per il merge nel branch principale, ma nell’attesa puoi fare la modifica sul tuo .py riga 493/494….direi…

 

Da: ***@***.*** ***@***.***> 
Inviato: mercoledì 12 ottobre 2022 16:47
A: 'muchasuerte/ha-besmart' ***@***.***>; 'muchasuerte/ha-besmart' ***@***.***>
Cc: 'Comment' ***@***.***>
Oggetto: R: [muchasuerte/ha-besmart] Stato batteria (Issue #9)

 

Effettivamente adesso che mi funziona (stranamente 😝 ) la app anche la mia batteria scarica non viene piu’ segnalata.

Io mi ero appoggiato al codice di muchasuerte non ho le competenze necessarie per verificare se il valore dello status batteria viene ancora esportato correttamente verso HA, ci tocca aspettare lui o altri volenterosi…

 

Da: PaulusThe1 ***@***.*** ***@***.***> > 
Inviato: martedì 11 ottobre 2022 11:28
A: muchasuerte/ha-besmart ***@***.*** ***@***.***> >
Cc: faxbio ***@***.*** ***@***.***> >; Comment ***@***.*** ***@***.***> >
Oggetto: Re: [muchasuerte/ha-besmart] Stato batteria (Issue #9)

 

Io mi collego regolarmente sia con l'app BeSmart che con HomeAssistant
-------- Messaggio originale --------Da: faxbio ***@***.*** <mailto:***@***.***> > Data: 11/10/22 10:53 (GMT+01:00) A: muchasuerte/ha-besmart ***@***.*** <mailto:***@***.***> > Cc: PaulusThe1 ***@***.*** <mailto:***@***.***> >, Author ***@***.*** <mailto:***@***.***> > Oggetto: Re: [muchasuerte/ha-besmart] Stato batteria (Issue #9) 

Provo a darci un occhio appena riesco, ma in questi giorni il server

besmart è sempre offline ( o meglio , busy)...sicuro non sia quello?

Da app ti colleghi?



Il sab 23 lug 2022, 20:11 PaulusThe1 ***@***.*** <mailto:***@***.***> > ha scritto:

**Comment by muchasuerte** [comment]
Grazie @faxbio tra sabato/domenica provo a rivedere la tua modifica

**Comment by muchasuerte** [comment]
ho fatto il merge della modifica e testato su HA 2022 sembra tutto ok, ora incluso lo stato della batteria.

**Comment by muchasuerte** [comment]
faxbio ho fatto il merge e provado con HACS la modifica e sembra tutto funzionante con l'ultima versione di HA 2022.11

**Comment by sbusceti** [comment]
ciao, dove lo trovo il sensore di batteria? Ho cercato in home-assistant sia sotto dispositivi che sotto entità ma non trovo nulla

**Comment by muchasuerte** [comment]
Ciao ,

solitamente creo un sensore template

binary_sensor:
  - platform: template
    sensors:
      heating:
        friendly_name: "Heating"
        value_template: "{{ state_attr('climate.besmart_thermostat',
'hvac_action') == 'heating' }}"
      cooling:
        friendly_name: "Cooling"
        value_template: "{{ state_attr('climate.besmart_thermostat',
'hvac_action') == 'cooling' }}"
      thermostat_status:
        friendly_name: "Thermostat status"
        value_template: "{{ state_attr('climate.besmart_thermostat',
'heating_state') == true }}"
      battery_state:
        friendly_name: "battery state"
        device_class: battery
        value_template: "{{ state_attr('climate.besmart_thermostat',
'battery_state') == '1' }}"
        icon_template: mdi:battery

l'info della batteria e' riportato come parte delle informazioni extra del
termostato
